AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  TableName:
    Type: String
    Default: "Carnus-xxxx"
  RawBucketName:
    Type: String
    Default: "carnus-raw-xxxx"
  ThumbBucketName:
    Type: String
    Default: "carnus-thumbs-xxxx"

Resources:
  CarnusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  RawSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RawBucketName

  ThumbnailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ThumbBucketName

  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      MemorySize: 1024
      Timeout: 5
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:445285296882:layer:perl-5-38-runtime-al2023-x86_64:1"
      Environment:
        Variables:
          PERL5LIB: "/opt/lib/perl5/site_perl/5.38.2:/opt/lib"
          TABLE_NAME: !Ref TableName
          THUMB_BUCKET: !Ref ThumbBucketName
      Policies:
        - S3ReadPolicy: { BucketName: !Ref RawBucketName }
        - S3WritePolicy: { BucketName: !Ref ThumbBucketName }
        - DynamoDBCrudPolicy: { TableName: !Ref TableName }
        - RekognitionDetectOnlyPolicy: {}
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref RawSourceBucket
            Events: s3:ObjectCreated:*
